import type { NextPage } from "next";
import Head from "next/head";
import Button from "@mui/material/Button";
import Container from "@mui/material/Container";
import TextField from "@mui/material/TextField";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";

const Home: NextPage = () => {
  return (
    <Container maxWidth="xs">
      <Head>
        <title>NestJS Practice UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box height="100vh" display="flex" alignItems="center">
        <Grid container spacing={2} component="form" autoComplete="off">
          <Grid item xs={12}>
            <Box sx={{ typography: "subtitle1", textAlign: "center" }}>
              <h1>Simple User CRUD</h1>
            </Box>
          </Grid>

          <Grid item xs={12}>
            <TextField
              id="email"
              label="Email"
              type="email"
              variant="outlined"
              fullWidth
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              label="Password"
              type="password"
              variant="outlined"
              fullWidth
            />
          </Grid>

          <Grid item xs={12}>
            <Button variant="outlined" size="large" fullWidth>
              Login
            </Button>
          </Grid>

          <Grid item xs={12}>
            <Button variant="contained" size="large" fullWidth>
              Sign up
            </Button>
          </Grid>
        </Grid>
      </Box>
    </Container>
  );
};

export default Home;
